function WB = white_board(row,col,dim,band,spectralon_pp_dir,spectralon_pp_fname_base);

WB = zeros(row,col);

for K = 1:min(9,dim);
    %display(int2str(K));
    img = fitsread([spectralon_pp_dir,'/',spectralon_pp_fname_base,'-00',int2str(K),'F',int2str(band),'.fit']);
    mask = double(imread([spectralon_pp_dir,'/',spectralon_pp_fname_base,'-00',int2str(K),'_mask.png']))./255;
    img = img.*mask;
    for I = 1:row;
        for J = 1:col;
            WB(I,J) = max(WB(I,J),img(I,J));
        end;
    end;
end;
if(dim>9);
    for K = 10:dim;
        %display(int2str(K));
        img = fitsread([spectralon_pp_dir,'/',spectralon_pp_fname_base,'-0',int2str(K),'F',int2str(band),'.fit']);
        mask = double(imread([spectralon_pp_dir,'/',spectralon_pp_fname_base,'-0',int2str(K),'_mask.png']))./255;
        img = img.*mask;
        for I = 1:row;
            for J = 1:col;
                WB(I,J) = max(WB(I,J),img(I,J));
            end;
        end;
    end;
end;
WB_max = zeros(row,col);
for I = 1:row;
    for J = 1:col;
        value = 0;
        i_lo = max(1,I-2);
        i_hi = min(row,I+2);
        j_lo = max(1,J-2);
        j_hi = min(col,J+2);
        for i = i_lo:i_hi;
            for j = j_lo:j_hi;
                value = max(value,WB(i,j));
            end;
        end;
        WB_max(I,J) = value;
    end;
end;
WB = WB_max;